apiVersion: chaosblade.io/v1alpha1
kind: ChaosBlade
metadata:
  name: pod-network-loss-by-names
spec:
  experiments:
  - scope: pod
    target: network
    action: loss
    desc: "pod network loss"
    matchers:
    - name: labels
      value:
      - "app=bank-account-scala"
    - name: percent
      value: ["1"]
    - name: interface
      value: ["eth0"]
    - name: namespace
      value:
      - "kafka"
