apiVersion: chaosblade.io/v1alpha1
kind: ChaosBlade
metadata:
  name: pod-mem-load
spec:
  experiments:
  - scope: pod
    target: mem
    action : "load"
    desc: "increase pod mem load by labels"
    matchers:
    - name: labels
      value:
      - "app=bank-account-scala"
    - name: mode
      value:
      - "ram"
    - name: mem-percent
      value:
      - "80"
    - name: namespace
      value:
      - "kafka"
